#!/bin/bash
DIST_HOME="$(dirname $(readlink $0 || echo $0))/../.."
source $DIST_HOME/scripts/base.sh
TEST_JAR=$(find_test_jar $DIST_HOME)
java -server -classpath "$DIST_HOME/libs/*:$TEST_JAR" net.lag.kestrel.load.JournalPacking "$@"
